#!/bin/bash
sum=0; for i in $(echo $WATER | grep -o .); do sum=$((sum + $(echo "ewwatratewa" | grep -o . | grep -n $i | cut -d: -f1))); done; for i in $(echo $STIR | grep -o .); do sum=$((sum + $(echo "ti.itirtrtr" | grep -o . | grep -n $i | cut -d: -f1))); done; echo $sum | rev

